{% set name = "mypy_extensions" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75dbf8955dc00442a438fc4d0666508a9a97b6bd41aa2f0ffe9d2f2725af0782

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - mypy_extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Experimental type system extensions for programs checked with the mypy typechecker.
  description: |
    The 'mypy_extensions' module defines experimental extensions to the
    standard 'typing' module that are supported by the mypy typechecker.
  doc_url: https://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy/blob/master/extensions

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
