appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HT/RW/KDW57rKB8JTCdQx0mVTPuDtnvwcR7N+CRjT7i6lptkVF4H2U+NL0OwUHg32y5G7njzKys4usd8VUPaz8fRbpKOBZXv9+82Xcqn1+Wk3gDtMTyIsPrjOslUPOYvl3QzbV0k6RUkLBnwLX/C8EFlp59/OonWICgmRYNxCjjFxiiSBA97vJ4qLNoBV5Xb+I21bsUTWZPcwFwxLOjIeGom53NaSqWRyNKNvGxRdL6UxXKA5tDF7lfkKgHzny9O5qqbeqyYZLmZWWNrlg7eTVAcLHniXcYdzC8yP/5oEEZ9OS0mk0j5vI85avmoshEkuhS9zScIZIBW44tkAMIgmBAo8x83FvkexSugmor2w3/n9rTs5x4vEeCmtYHbH6YURdedkDpfXmomHt0A6KwKiyP1AQ7oQxYA646hJrhfN0Go4dOhI268bXzTutUOZkCrRhv/86T01MtBEIrwUrbNLiG58J2+UmDJ8MBoYInbZZy3+HJel2/TErsFH6N9ZdPHpYSHDF/LpqZjwN7JccmKciE10pIebMottnXZ3z6kKCbBAvCO8eaObHpH/Gil/4exPTJj5HfVDuBFJyjOOOYkaa3P/rDsY+OR9KeVlJjXhWCFdYddCw45Q0AR2hzZNLSdrDAmaaOMLvFvfgttnYKNtfQUdLTicCHJ371cPA5c3T0=}
